# Generated by Django 5.2.4 on 2025-08-30 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='banks_Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('description', models.TextField(blank='', verbose_name='description')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='banks/', verbose_name='avatar')),
                ('is_enable', models.BooleanField(default=True, verbose_name='is enable')),
                ('credentials', models.TextField(blank=True, verbose_name='credentials')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'INITIAL'), (100, 'SUCCESSFUL'), (200, 'FAILED'), (300, 'CANCELLED'), (400, 'REFUND')], db_index=True, default=0, verbose_name='status')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('phone_number', models.BigIntegerField(db_index=True, verbose_name='phone number')),
                ('consumed_code', models.PositiveIntegerField(db_index=True, null=True, verbose_name='tracking code')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='modification time')),
                ('bank_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peyments.banks_gate', verbose_name='bank_port')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plans', verbose_name='package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'db_table': 'transaction',
            },
        ),
    ]
