# Generated by Django 5.2.4 on 2025-08-31 06:56

import utils.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peyments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.BigIntegerField(db_index=True, validators=[utils.validation.PhoneNumberValidator()], verbose_name='phone number'),
        ),
    ]
