# Generated by Django 5.2.4 on 2025-09-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peyments', '0002_alter_transaction_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.CharField(null=True),
        ),
    ]
