# Generated by Django 5.2.4 on 2026-07-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peyments', '0003_transaction_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banks_gate',
            options={'verbose_name': 'bank gate', 'verbose_name_plural': 'banks Gate'},
        ),
        migrations.AlterModelTable(
            name='banks_gate',
            table='banks Gate',
        ),
    ]
