# Generated by Django 5.2.4 on 2026-07-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peyments', '0004_alter_banks_gate_options_alter_banks_gate_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
