# Generated by Django 5.2.4 on 2025-08-30 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('sku', models.CharField(db_index=True, verbose_name='code adnbar')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='planes/', verbose_name='picture')),
                ('discreaption', models.TextField(blank=True, verbose_name='discreaption')),
                ('price', models.IntegerField(verbose_name='price')),
                ('is_enable', models.BooleanField(default=True, verbose_name='is enable')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='active time')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time', models.DateTimeField(auto_now_add=True, verbose_name='active time')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='expire')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'user subscriptions',
            },
        ),
    ]
