# Generated by Django 5.2.4 on 2025-08-31 06:56

import utils.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='sku',
            field=models.CharField(db_index=True, validators=[utils.validation.SKUValidator()], verbose_name='code adnbar'),
        ),
    ]
