# Generated by Django 5.2.4 on 2025-08-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='برای اینکه مشخص شود اکانت فعال است یا خیر', verbose_name='is_active'),
        ),
    ]
