# Generated by Django 5.2.4 on 2026-07-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('MALE', 'آقا'), ('FEMALE', 'خانم'), ('UNKNOWN', 'عدم تمایل به ذکر')], default='UNKNOWN', max_length=20, verbose_name='جنسیت'),
        ),
    ]
