# Generated by Django 5.2.4 on 2025-08-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='avatar',
            new_name='file',
        ),
    ]
