# Generated by Django 5.2.4 on 2025-08-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_avatar_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'movie'), (2, 'audio'), (3, 'file')], default=1, verbose_name='produc type'),
        ),
    ]
