# Generated by Django 5.2.4 on 2025-09-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(default='General', max_length=50, verbose_name='genre'),
        ),
    ]
