# Generated by Django 5.2.4 on 2025-09-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_parent_product_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(max_length=50, verbose_name='genre'),
        ),
    ]
